Feat 18 로그인, 회원가입 코드 리팩토링 및 소셜 로그인 구현
arsgsg1/Mediate pull request #32
Opened 2022-10-12 08:55 UTC by lyle0101

- AuthService, TokenProvider, TokenStorage 가 있는 jwt 패키지 부분을 전체적으로 리팩토링 하였습니다.
- Google, Kakao, Naver 소셜 로그인을 구현하였습니다.

2022-10-14 07:05 UTC, arsgsg1 requested changes

2022-10-14 07:12 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/auth/domain/Account.java
> +    private SocialType socialType;
두 가지 모두 제가 빠뜨린 부분이군요ㅎㅎ: 저도 당연히 EnumType.STRING 으로 해야한다고 생각합니다. 수정해놓을게요!

2022-10-19 09:51 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/jwt/TokenProvider.java
> +            return false;
기존 코드가 예외도 던지고 있고 true, false 반환도 하고 있어서 둘 중에 하나만 하게 하려고 바꾼건데 나중에 디버깅하기 좋으려면 예외를 그냥 던지는 식으로 바꾸는게 낫겠네요!

2022-10-19 09:52 UTC, lyle0101 commented on src/main/java/com/ko/mediate/HC/auth/application/AuthService.java
> +        assert tokenProvider.isValidToken(refreshToken);
말씀하신대로 assert 를 사용하면 어떤 예외가 발생했는지 알기 어려우니 아래 코멘트와 마찬가지로 isValidToken 을 validateToken 으로 바꾸고 예외를 던지는 메서드로 바꿔야 겠네요!

2022-10-24 13:24 UTC, closed without merging